---
id: passwd
name: Passwd
full: Password changing application
description: >-
  An application to change any user passwords stored in various backends like
  SQL, LDAP, Kolab, passwd files etc.
list: sork
type: application
homepage: https://www.horde.org/apps/passwd
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 6.0.0alpha2
  api: 6.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: GPL-2.0
  uri: http://www.horde.org/licenses/gpl
dependencies:
  required:
    php: ^7
    composer:
      horde/horde: ^6
      horde/auth: ^3
      horde/core: ^3
      horde/exception: ^3
      horde/injector: ^3
      horde/util: ^3
      horde/view: ^3
    ext:
      gettext: '*'
  optional:
    composer:
      horde/db: ^3
      horde/http: ^3
      horde/ldap: ^3
      horde/vfs: ^3
    pear:
      pear/crypt_chap: ^2
    ext:
      com: '*'
      ldap: '*'
      soap: '*'
