<?php
// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/passwd/routes.local.php and run composer horde:reconfigure
namespace Horde\Passwd;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

// Responsive UI Routes - PSR-style builder pattern

// Responsive Password Change - Primary route with legacy smartmobile secondary
$mapper->buildRoute(uri: '/responsive', name: 'ResponsivePassword')
    ->withController(ResponsivePasswordController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->noMiddleware()
    ->withSecondaryRoute('/smartmobile')
    ->withSecondaryRoute('/smartmobile.php')
    ->add();
